/left/controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_effort_controller:
      type: effort_controllers/JointGroupEffortController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    force_mode_controller:
      type: ur_controllers/ForceModeController

    freedrive_mode_controller:
      type: ur_controllers/FreedriveModeController

    passthrough_trajectory_controller:
      type: ur_controllers/PassthroughTrajectoryController

    tcp_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

    passthrough_trajectory_controller:
      type: ur_controllers/PassthroughTrajectoryController

    ur_configuration_controller:
      type: ur_controllers/URConfigurationController

    tool_contact_controller:
      type: ur_controllers/ToolContactController

/left/speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "left_"

/left/io_and_status_controller:
  ros__parameters:
    tf_prefix: "left_"

/left/ur_configuration_controller:
  ros__parameters:
    tf_prefix: "left_"

/left/force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: left_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: left_tool0
    topic_name: ft_data


/left/joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      left_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      left_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      left_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }


/left/scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      left_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      left_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      left_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: left_speed_scaling/speed_scaling_factor

/left/passthrough_trajectory_controller:
  ros__parameters:
    tf_prefix: "left_"
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: left_speed_scaling/speed_scaling_factor

/left/forward_velocity_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    interface_name: velocity

/left/forward_effort_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    interface_name: effort

/left/forward_position_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

/left/force_mode_controller:
  ros__parameters:
    tf_prefix: "left_"

/left/freedrive_mode_controller:
  ros__parameters:
    tf_prefix: "left_"

/left/tcp_pose_broadcaster:
  ros__parameters:
    frame_id: left_base
    pose_name: left_tcp_pose
    tf:
      child_frame_id: left_tool0_controller

/left/tool_contact_controller:
  ros__parameters:
    tf_prefix: "left_"
