controller_names:
  - left_scaled_joint_trajectory_controller
  - right_scaled_joint_trajectory_controller

left_scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint


# left_joint_trajectory_controller:
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   default: false
#   joints:
#     - left_shoulder_pan_joint
#     - left_shoulder_lift_joint
#     - left_elbow_joint
#     - left_wrist_1_joint
#     - left_wrist_2_joint
#     - left_wrist_3_joint

right_scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint


# right_joint_trajectory_controller:
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   default: false
#   joints:
#     - right_shoulder_pan_joint
#     - right_shoulder_lift_joint
#     - right_elbow_joint
#     - right_wrist_1_joint
#     - right_wrist_2_joint
#     - right_wrist_3_joint